### PR TITLE
Close issue #217: ngOutletContext to ngTemplateOutletContext

### PR DESCRIPTION
**Pull request by FallenRiteMonk**
Support for ionic 3.9.2 and angular 5.0.0

### CODE REVIEW

**Comment by FallenRiteMonk** [comment]
You might have to update angular to 4.x or higher. I haven#t done it since I wasn't sure and didn't have the time to try it!

**Comment by twinssbc** [comment]
@FallenRiteMonk Thanks for the PR. I'm aware of the breaking change of Angular 5.0.
I don't want to merge this PR to master branch.
Because I'm maintaining two branches now, master branch is for Ionic2 and Angular2, v3 is for Ionic3 and Angular4.
In this way, I could easily apply fix and do release build for both versions.
I will create a v4 branch and merge your code into it.

**Comment by tonirilix** [comment]
Thx @twinssbc for the time and effort you have put into creating and maintaining this plugin.

**Comment by FallenRiteMonk** [comment]
@twinssbc Thanks for the info and the effort. Do you have any plan on when this is going to happen, because I'd be really interested in getting this into my project?

**Comment by twinssbc** [comment]
I have released 0.4.0 which supports Ionic 3.9.2. Feel free to have a try.

**Pull request closed without merging**
