### PR TITLE
Day selection in week

### PR DESCRIPTION
**Pull request by lcaprini**
- Added `weekviewHeaderTemplate` template for day in week view header
- Added day selection with click on week view header
- Added `autoSelect` on week view
- Added `weekview-with-event`, `weekview-current` and `weekview-selected` css class for days in week view header (with commented style)

### CODE REVIEW

**Comment by kkaczmarzyk** [comment]
Sorry for dumb question but how can I use these changes? These are exactly those functionalities that I need.

**Comment by kkaczmarzyk** [comment]
Thank You for the quick answer! But I meant how can I add Your changes to the calendar. Is there a way to add them in a some sort of an automated way? Or I just need to add them by manually modifying files? Once again, thanks for the help.

**Comment by lcaprini** [comment]
You can try to install my fork at tag [day-selection-in-week-and-locale-change](https://github.com/lcaprini/Ionic2-Calendar/tree/day-selection-in-week-and-locale-change,) but is not aligned with the current master version.

**Comment by kkaczmarzyk** [comment]
Sorry, but I have never done something like that before. Would You be so kind as to show me how to do it?

**Pull request merged**
