### PR TITLE
added event_class property to an event

### PR DESCRIPTION
**Pull request by mihairadulescu**
i wanted to be able to add custom classes to an event cell.
merge this if you think it helps

### CODE REVIEW

**Comment by twinssbc** [comment]
@mihairadulescu 
In this way, your model and view are coupled together.
I would rather allow view customisation based on the event property.

**Comment by mihairadulescu** [comment]
can we add a custom view template now in the calendar?

**Comment by mihairadulescu** [comment]
@twinssbc maybe we should have a hangout to and discuss further improvements you have in mind. I`m open to contribute to features.

**Comment by twinssbc** [comment]
@mihairadulescu I have created a Project for this repository so that the progress can be tracked.

**Comment by twinssbc** [comment]
customized view option is already added

**Pull request closed without merging**
